### ISSUE TITLE
odoo 8

### ISSUE THREAD

**Issue by martinfpas** [gbisheimer/odoo-vagrant#3]
Hola, hace un tiempo use con mucho exito tu script para desrrollar en v7. Ahora estoy tratando de desarrollar en v8 y cuando hago "vagrant up" recibo este error. 

default: Error: Invalid parameter ensure at /tmp/vagrant-puppet-3/manifests/default.pp:68 on node vagrant.example.com

Ideas?

**Comment by martinfpas** [comment]
Supere la traba mandandome de cabeza. Vos me diras que tan descabellado es.
Comente la linea 63 donde esta el parametro “ensure” en default.pp

class { 'postgresql::server':
  #ensure => 'lastest',
  ip_mask_deny_postgres_user => '0.0.0.0/32', # Allows posgres user connection from any host
  ip_mask_allow_all_users    => '0.0.0.0/0',
  listen_addresses => '*',
  postgres_password => 'postgres',            # Sets default postgres user password
}

Despues de eso hice Vagrant provision y anduvo.

Aguardo tus comentarios

**Comment by gbisheimer** [comment]
@martinfpas, recién veo estos comentarios. Sucede que el plugin de postgresql para puppet cambió desde que escribí este script y me faltó actualizarlo.

Ahora subo la actualización. Gracias por comentar!
